name: Arena Allocator CI
on: [push, pull_request]
env:
  CARGO_TERM_QUIET: "true"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test and coverage
        run: |
          cargo test
          cargo install cargo-llvm-cov
          cargo llvm-cov --fail-under-lines 90 --all-features
        
